name: TheYouthsportscenter
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: 'The YSC Grid 100 News & Information'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fe002f'
    - '#fee200'
    - '#fe90b5'
    - '#00aa90'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 1
purpose: []
