name: TheYouthsportscenter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9960823522415012
title: 'The YSC Grid 100 News & Information'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feff5c'
    - '#010005'
    - '#fd235d'
    - '#3fa06a'
    - '#eb9189'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
