name: TheYouthsportscenter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9960823522415012
title: 'The YSC Grid 100 News & Information'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20162f'
    - '#f1fbfd'
    - '#565abb'
    - '#eecbb7'
    - '#d36443'
  brandStrength: 0.8125
  lightness: 0.822466152952984
  saturation: 0.1405978745315224
  rhythmicContrast: 0.14479804295115173
purpose: []
