name: TheYouthsportscenter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9960823522415012
title: 'The YSC Grid 100 News & Information'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff1e2e'
    - '#565455'
    - '#63fe02'
    - '#a9bb10'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
