name: TheYouthsportscenter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9960823522415012
title: 'The YSC Grid 100 News & Information'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020a21'
    - '#ffffff'
    - '#75aecc'
    - '#9c5b28'
    - '#f4ab32'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
