name: TheYouthsportscenter
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9960823522415012
title: 'The YSC Grid 100 News & Information'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#505050'
    - '#00fdfb'
    - '#af0000'
    - '#fd4a0f'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
